version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sampledb
    ports:
      - "5432:5432"
   
  adminer:
    image: adminer:latest
    container_name: adminer_ui
    ports:
      - "8080:8080"
